### ISSUE TITLE
Entry needs to be in shr.base namespace

### ISSUE THREAD

**Issue by notpace** [standardhealth/shr-cli#106]
In an attempt to create a set of `cimpl.core` definitions (de-branding from `shr`), the following warning popped up:
```
[17:30:56.520Z]  WARN shr: Could not find expanded definition of shr.base.Entry. Inheritance calculations will be incomplete. ERROR_CODE:12036 (module=shr-expand)
```
The `Entry` definition was present in the file, but the compiler is specifically looking for it in the `shr.base` namespace.

**Comment by notpace** [comment]
This is related to #70

**Comment by markkramerus** [comment]
Closing. This task is underway as SHRO-819.
