### ISSUE TITLE
Syntax for individually addressing sliced output fields

### ISSUE THREAD

**Issue by notpace** [standardhealth/shr-cli#108]
Since the slicing commands do not create unique CIMPL names for each of the sliced output fields, it is impossible to `fix` or `constrain` individual slices in the output file.

For example:
```
ProviderApplication maps to Task:
  EFTAccepted maps to input (slice on = type)
  ProviderType maps to input
```
The [FHIR Task resource](https://www.hl7.org/fhir/task.html) includes an `input` field that can include an arbitrary number of items, each with arbitrary data types.  In the current CIMPL syntax, both the `fix` and `constrain` keywords assume that there is only one instance of the output target, but slicing breaks this paradigm.

Consider an update to the syntax that allows sliced output fields to be individually addressed, e.g.:
```
ProviderApplication maps to Task:
  EFTAccepted maps to input[0] (slice on = type)
  fix input[0] to true
  ProviderType maps to input[1]
```

**Comment by markkramerus** [comment]
Pace, we are wondering why you don't constrain before you slice. At least that might be a workaround.

**Comment by notpace** [comment]
If I recall correctly, I was attempting to model something relatively generic (which I expected to be re-used as an element for subsequent data modeling) and specialize it in the mapping.  I think I can accomplish the same end goal using additional data elements `Based on` the more generic one in the mapping file, but it would really be nice to have the ability to do things either way.

**Comment by markkramerus** [comment]
I can imagine when profiling a profile, there could be a need to further constrain a slice (including setting the cardinality of that slice to 0..0, doing a VS binding to a property in the slice. We should investigate this. Moving to Tasks (https://jira.mitre.org/browse/SHRO-958)
