### ISSUE TITLE
Duplicate Elements are not detected and flagged

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-cli#111]
We had a situation where accidentally we had twice defined SubjectOfInformation and it compiled fine. This should be flagged.

**Comment by cmoesel** [comment]
Hmmm... I thought we would error on this, but I guess not.  Both `SubjectOfInformation` definitions were in the _same_ namespace?

**Comment by markkramerus** [comment]
I might have to walk this one back. I wasn’t able to reproduce it.

**Comment by markkramerus** [comment]
Yes, same namespace. I was compiling with -s all, if that makes a difference.

**Comment by cmoesel** [comment]
Actually, I can reproduce this -- so it's a real bug.

**Comment by markkramerus** [comment]
This was fixed some time ago.
