### ISSUE TITLE
shr-cli -c option is ignored and defaults to config.json

### ISSUE THREAD

**Issue by mlterryMitre** [standardhealth/shr-cli#112]
tested/debugged and confirmed behavior with @kjmahalingam.  
Workaround is to copy the custom -config.json configuration to the default config.json.

On a side note, the last merge to master for shr_spec has a default config.json that is specific to the occupational health SHR work.  This should probably be changed back to a generic config.json.

**Comment by cmoesel** [comment]
@kjmahalingam and I just discussed this issue.  There are two problems at play here:

1. The code currently requires that the path you pass in ends with a trailing path separator (e.g., `node . -c my-config.json ../shr_spec/spec/` works, but `node . -c my-config.json ../shr_spec/spec` does not).

2. The code currently requires that the config file end with `config.json` or `config.txt` (e.g., `node . -c my-config.json ../shr_spec/spec/` works, but `node . -c my-configuration.json ../shr_spec/spec/` does not).  Some of the config file's in shr_spec's shimi branch end with `configuration.json`.

I'll work on a fix and we can release a new SHR-CLI once it's been reviewed and merged.

**Comment by cmoesel** [comment]
In the mean time, you can get around this by making sure you pass in the trailing path separator (`\` on windows, `/` on mac) _and_ making sure your config file ends with `config.json`.

**Comment by kjmahalingam** [comment]
Thanks for locating this issue, @cmoesel. Note that with this change, we should remove that line in the SHR-CLI README that refers to the file ending in `config.json` as that will no longer be relevant.

**Comment by cmoesel** [comment]
Fixed in [SHR-CLI 5.9.1](https://github.com/standardhealth/shr-cli/releases/tag/v5.9.1).
