### ISSUE TITLE
Generated FHIR IG shows incorrect symbol for "sigma"

### ISSUE THREAD

**Issue by mlterryMitre** [standardhealth/shr-cli#113]
The FHIR Flags column in the SHR generated FHIR IG is not showing the right special character (namely sigma for the summation symbol).  See screenshot below.
![image](https://user-images.githubusercontent.com/40579130/42707625-d0eace48-86a8-11e8-93aa-77b64b56badb.png)

**Comment by markkramerus** [comment]
Fixed in IG publisher. It wasn't our bug.
