### ISSUE TITLE
Logical Model for Encounter has no attributes.

### ISSUE THREAD

**Issue by mlterryMitre** [standardhealth/shr-cli#115]
Identified in the Breast Cancer Model FHIR IG May 2018 Ballot Comment [#16167](https://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=16167&start=0).  

The FHIR IG EncounterModel (http://hl7.org/fhir/us/breastcancer/StructureDefinition-cimi-Encounter-model.html) shows no attributes.

From discussions on the ballot:
...the "stubbed out" nature of Encounter reflects a tooling limitation in trying to put a boundary around the classes described in the Implementation Guide.
We propose to resolve this through better explanation rather than a technical fix.

The problem is that a domain-specific class A could link to non-domain class B, which involves non-domain class C, and eventually, the IG contains more content from outside the domain, than from the domain itself. For this IG, stubbing out Encounter was a crude way to limit the scope of the BreastCancer IG. In the future, we would like to develop better ways to publish modules/namespaces as separate IG "libraries" that cross-reference each other.

**Comment by markkramerus** [comment]
We handle this now through the "no profile" declaration in the content profiles. "Stubbing out" in the model is not required.
