### ISSUE TITLE
FHIR IG Publisher does not recognize LOINC answer list IDs (LL- and LA- codes)

### ISSUE THREAD

**Issue by mlterryMitre** [standardhealth/shr-cli#117]
Grahame Grieve states that the FHIR TX server used for the FHIR IG Publisher does support this.
While he pointed to the URL which shows the response to a ValueSet request for a given answer list ([LL715-4](https://fhir.loinc.org/ValueSet/LL715-4/$expand)), I was not able to get this response sending the request to tx.fhir.org/r4 nor tx.fhir.org.

cc: @cmoesel to help debug this issue.

**Comment by mlterryMitre** [comment]
Resolved - @cmoesel found that references to LOINC answer lists are authored in CIMPL using the following syntax:
http://loinc.org/vs/<the LL- number>

Example Syntax: ObservationContext.ResultValue should be from http://loinc.org/vs/LL240-3

**Comment by cmoesel** [comment]
Related zulip chat: https://chat.fhir.org/#narrow/stream/99-IG-creation/topic/Supporting.20LOINC.20Answer.20Lists.3F

**Comment by cmoesel** [comment]
Grahame has confirmed that this is likely a bug in the tooling or terminology server and that it is "on the list" (but that list is long).

**Comment by markkramerus** [comment]
We are successfully using "LA" codes in mCODE. Closing.
