### ISSUE TITLE
Running the FHIR IG publisher generates an illegal reflective access operation warning.

### ISSUE THREAD

**Issue by mlterryMitre** [standardhealth/shr-cli#119]
Discovered while debugging issue #117 with @cmoesel .
The warning doesn't appear to be critical and the FHIR IG still generates successfully, but here's the message anyway:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.poi.util.DocumentHelper (file:/Users/mayt/cimpl/shr-cli/out/fhir/guide/org.hl7.fhir.igpublisher.jar) to method com.sun.org.apache.xerces.internal.util.SecurityManager.setEntityExpansionLimit(int)
WARNING: Please consider reporting this to the maintainers of org.apache.poi.util.DocumentHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by cmoesel** [comment]
This is an issue in one of the dependencies of the FHIR publisher (the "POI" dependency) -- and is specifically related to changes in Java 9 / 10.  If you run using Java 8, you will not encounter this error.

Official bug report (for POI) is here -- but it looks like they don't have a plan yet:
https://bz.apache.org/bugzilla/show_bug.cgi?id=62151

The FHIR Publisher docs aren't very clear about what version of Java to use, but it seems like Java 8 might be best for now.

Link to relevant Zulip chat (that I just started): https://chat.fhir.org/#narrow/stream/99-IG-creation/topic/Java.2010.20and.20Illegal.20reflective.20access.20operation

**Comment by markkramerus** [comment]
OBE.
