### ISSUE TITLE
SpecificFocusOfFinding generates error in shr-json-schema-export

### ISSUE THREAD

**Issue by mlterryMitre** [standardhealth/shr-cli#123]
**Example:** 
Consider 2 EntryElements : CancerDisorder and CancerStage.  Both successfully compile without SpecificFocusOfFinding.

I add the following line in CancerStage:
`SpecificFocusOfFinding value is type CancerDisorder` 

What happens...
shr-cli generates the following error:
"**ERROR** shr: Target of an unnormalized constraint: TypeConstraint (mcode.CancerDisorder, on value: true, on path:) was a choice value that did not have a valid option: shr.base.SpecificFocusOfFinding (module=shr-json-schema-export, shrId=mcode.CancerStage)"

Reviewed with @cmoesel , who suspects it might be related to a limitation or a bug in the JSON schema exporter and shouldn't impact the generation of the IG.
To suppress the json exporter schema error, run shr-cli using the _-s json-schema_ parameter.

I re-inserted the SpecificFocusOfFinding syntax above, re-run shr-cli and am able to successfully generate the FHIR IG, however the generated CancerStage FHIR Profile in `shr-base-SpecificFocusOfFinding-extension` is still missing the reference to CancerDisorder.

cc: @markkramerus , @rutemartins

**Comment by markkramerus** [comment]
It should be **SpecificFocusOfFinding value is type ref(CancerDisorder)** -- note ref( ). This prevents the error in some cases, it appears. 
The other workaround is to get rid of the choices in SpecificFocusOfFinding.Value. If it is just ref(InformationItem), the errors disappear.
Still needs to be fixed, and a better error message would be helpful; something along the lines of "Hey, modeler, you forget the ref!".

**Comment by mlterryMitre** [comment]
@cmoesel and @markkramerus  - I see as of shr-cli shr-cli-5.12.0, I'm able to see SpecificFocusOfFinding now exporting without errors and associated correctly in the FHIR IG profiles.  Was this a change to shr-cli or fixed with the correct CIMPL syntax?
For example, `SpecificFocusOfFinding value is type ref(CancerDisorderPresent)` shows correctly in the IG.
Once we get clarification on the fix, we can close this ticket. Thanks!

**Comment by cmoesel** [comment]
I fixed the bug in the json-schema-exporter that was causing errors.  As for the correct insertion into the profile, I don't remember any specific bug fixes that would have addressed this, but... the DSTU2 support did change a fair bit of code, so I might have unintentionally fixed it?

**Comment by mlterryMitre** [comment]
Since the fix addresses the issue title for the error, I'll close the ticket.  Thanks!
