### ISSUE TITLE
npmName is now required by the FHIR IG publisher

### ISSUE THREAD

**Issue by notpace** [standardhealth/shr-cli#126]
Using 5.11, I generated some FHIR profiles and ran the IG generator, which returned the following:
```
Publishing Content Failed: A package name (npm-name) is required to pubish implementation guides. For further information, see http://wiki.hl7.org/index.php?title=FHIR_NPM_Package_Spec#Package_name
```

This field should be added to the example `config.json` file and to the shr-cli README to make sure users know it is required.

**Comment by cmoesel** [comment]
I've updated the README to at least reflect the two new fields (`npmName` and `version`).  I think that updating the example `config.json` needs to happen in another repo (if I recall, shr-text-import?).

**Comment by markkramerus** [comment]
Should have been closed since fix was committed.
