### ISSUE TITLE
"Cannot unroll.. create an explicit choice element first" error (13009)

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-cli#130]
In FHIMI2, you'll get this error if you uncomment line 189 in shr_occupation.txt. It's trying to fix units on a quantity choice within FindingResult, as follows: FindingResult.Quantity.Units is UCUM#d.
I've tried various different syntaxes with this but I think it is a problem in the framework.

**Comment by cmoesel** [comment]
Yes, I've actually been working on this one.  It's turning out to be trickier than expected -- there are some nuances around the extension handling that are causing complications...  But the fix is in progress.

**Comment by markkramerus** [comment]
This bug report is quite old, and I haven't seen this issue in a long time. Closing.
