### ISSUE TITLE
Mapping to a slice of extensions generates error in fhir export

### ISSUE THREAD

**Issue by mlterryMitre** [standardhealth/shr-cli#134]
The FHIR DSTU genetics profile (https://hl7.org/fhir/DSTU2/genetics.html) has a slice of components which are in themselves extensions and also include different data types.
Mapping the SHR elements to these elements to its equivalent FHIR attributes, the SHR compile fails with the following error message: 
_Cumulative slice min cardinalities (1) exceed the max cardinality (0) for the containing array at Extension:oncocore-GenomicSourceClass.extension._

Discussed with @cmoesel - this is a new use case and will require a feature enhancement. 
cc: @markkramerus

**Comment by cmoesel** [comment]
I noticed it also gives the following error:
```
[22:31:17.622Z] ERROR shr: Incompatible cardinality (using aggregation). Source cardinality 0..1 does not fit in target cardinality 1..1. ERROR_CODE:13017 (module=shr-fhir-export, shrId=oncocore.GenomicSourceClass, mappingRule="FindingResult maps to valueCodeableConcept")
```

But what's interesting is if I change the mapping of `FindingResult` so it is like this:
```
GenomicSourceClass maps to http://hl7.org/fhir/StructureDefinition/geneticsGenomicSourceClass:
    FindingResult maps to value[x]
```
then the errors go away.  That said, I'm not convinced it's actually working -- because I don't know why that would make a difference.   This will require further investigation.

**Comment by mlterryMitre** [comment]
Thanks for the update, @cmoesel.  You're right that the error went away, but it's not mapping - the  EntryElement is still showing up as a separate component.

**Comment by markkramerus** [comment]
I am not sure whether there is a requirement lurking here or not. Mapping an Entry to an extension should be illegal. Mapping an element to an existing extension is supported, although when that extension occurs on a nested element (anywhere but at the top level), we have a problem (Saul reported this and it is an open issue.) I'm going to close this issue and let the objections fly if anyone thinks that is inappropriate.
