### ISSUE TITLE
"ERROR shr: Cannot resolve element definition" needs an shr-cli error code assigned.

### ISSUE THREAD

**Issue by mlterryMitre** [standardhealth/shr-cli#140]
If one has an incorrect namespace in the map file, the error output is "ERROR shr: Cannot resolve element definition." and does not include an shr-cli error code.

Once a code is assigned, we can then document the solution to ensure that there is a viable StructureDefinition URL.

**Comment by markkramerus** [comment]
This is still a bug in 6.6.0. Moving to JIT (Jira Issue Tracker).
