### ISSUE TITLE
ModelDoc shows wrong cardinality on value choices

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-cli#157]
The wrong cardinality (0..*) is coming up in the ModelDoc for elements with value choices. Although it doesn't carry the meaning of one value being required, it is better to indicate 0..1 for each choice.  (If there is no value choice, the cardinality is given as 1..1, which is correct).  

See below for example...
```
Element:		PractitionerOrRelatedPerson
Based on:	EntityOrRole
Value:		ref(Practitioner) or ref(RelatedPerson)
```

<img width="310" alt="snipmodeldoc" src="https://user-images.githubusercontent.com/492232/52660057-d861b980-2ecc-11e9-8213-e3a24df0ba87.PNG">

**Comment by cmoesel** [comment]
Agreed.  This looks incorrect.  We'll need to look into it.

**Comment by markkramerus** [comment]
Moved to CIMPL-37. Closing.
