### ISSUE TITLE
Install Instruction Question

### ISSUE THREAD

**Issue by saulakravitz** [standardhealth/shr-cli#167]
Documentation says to install jdk 10...when I go to install jdk 10 I'm told that jdk 10 is obsolete, and redirected to jdk 12.   
Is this OK? 
If so, should documentation be updated?

**Comment by cmoesel** [comment]
The JDK is only needed for running the HL7 IG Publisher jar (to produce the full IG documentation).

The IG Publisher jar, however, requires _JDK 8_.  The documentation that says JDK 10 is incorrect.  I will fix it (as soon as I find it).

**Comment by cmoesel** [comment]
Thank you for reporting this.  I've updated the documentation [here](https://github.com/standardhealth/shr-cli/wiki/CIMPL-Installation#windows-java-installation).  Please let us know if you have any further questions.

**Comment by saulakravitz** [comment]
Dumb QUestion:    Is it obvious which is the latest version?
![image](https://user-images.githubusercontent.com/37216915/54948887-20d0b600-4f14-11e9-96f6-420df80595f0.png)

There is 8u201 and 8u202, both undated..

**Comment by cmoesel** [comment]
To be honest, I don't fully understand Java's numbering scheme, but in these cases I usually just pick the higher number (e.g., 202 is higher than 201, so I choose 8u202).
