### ISSUE TITLE
Extraneous "Value: " prefix in dictionary data type column

### ISSUE THREAD

**Issue by rutemartins** [standardhealth/shr-cli#171]
In the `Data Type` column, a `Value :` prefix sometimes appears. It seems to happen when the element _only_ has a `value` property, and no other properties. It's perfectly fine to present these in a single line, however we need to refactor the presentation. So, I'm seeing:

| Data Element Logical Path | Data Type |
|--- |--- |
| CancerCondition.Code | Value: CodeableConcept |

But I'd like to see:

| Data Element Logical Path | Data Type |
|--- |--- |
| CancerCondition.Code.Value | CodeableConcept |

**Comment by markkramerus** [comment]
Fixed some time ago.
