### ISSUE TITLE
Add value set content to data dictionary exporter

### ISSUE THREAD

**Issue by rutemartins** [standardhealth/shr-cli#180]
The data dictionary exporter needs an additional file exported that includes value set content for internally . This file should include:
1. The value set name
2. Value set description
3. Logical definition (for value sets defined with phrases such as `includes codes from [...]` or `includes codes descending from [...]`). If the value set is not logically defined, populate with `N/A`
4. Code (for value sets with enumerated codes). If the value set does not contain enumerated codes, populate with `N/A`.
5. Code description (for value sets with enumerated codes). If the value set does not contain enumerated codes, populate with `N/A`.
6. Code system(s): the code system associated with the enumerated code (or the logical definition).

**Note**: the same value set can include enumerated codes from several code systems, and may contain a mix of enumerated codes and logical definitions.

**Comment by markkramerus** [comment]
Added
