### ISSUE TITLE
Observation components and panel members not showing up in data dictionary export

### ISSUE THREAD

**Issue by rutemartins** [standardhealth/shr-cli#182]
Example: systolic and diastolic blood pressure.

**Comment by cmoesel** [comment]
I think you already know this, but it sounds like the data dictionary is missing the _includes type_ constraints on elements.

@garypgryan - _Includes type_ constraints allow the author to constrain an array of a base type to contain specific numbers of subtypes.  Non-clinical example: A `Zoo` might have `0..* Animal`.  A `PettingZoo` that is based on `Zoo` can say that the `0..* Animal` must include `2..* Goat`, `1..* Pony`, and `5..* Duck`.

Rute's clinical example is for `BloodPressure`.  `BloodPressure` is based on `Observation`, so it constrains `0..* Component` to include `1..1 SystolicPressure` and `1..1 DiastolicPressure`.

In the code, the _BloodPressure_ `DataElement`'s _Component_ `field` (an instance of `IdentifiableValue`) has `constraints`.  Two of those `constraints` are `IncludesTypeConstraint` ([source](https://github.com/standardhealth/shr-models/blob/master/lib/models.js#L1221-L1263)) constraints.  Each `IncludesTypeConstraint` has an `isA` property indicating that is included (in this case, one will be the identifier for _SystolicBloodPressure_ and the other will be _DiastolicBloodPressure).

**Comment by markkramerus** [comment]
Moved to CIMPL-33
