### ISSUE TITLE
Java Install Instructions for Mac Refer to Java10 (should be 8)

### ISSUE THREAD

**Issue by saulakravitz** [standardhealth/shr-cli#187]
https://github.com/standardhealth/shr-cli/wiki/CIMPL-Installation#fhir-ig-generation-tool-1

**Comment by cmoesel** [comment]
Well, shoot.  Apparently I fixed it in the Windows instructions but missed it in the Mac instructions.  Thanks for reporting it.

**Comment by cmoesel** [comment]
Fixed in the doc.
