### ISSUE TITLE
Jekyl Install on Mac (sudo -E)

### ISSUE THREAD

**Issue by saulakravitz** [standardhealth/shr-cli#188]
Took me a while to overcome this, so *might* be worth including in docs.
'gem install' on my mac requires sudo.   Sudo doesn't preserve env variables by default.
sudo -E gem install bundler jekyl
did the trick...sigh.

At least this will be searchable in the issues list for the next naive mac user.

**Comment by cmoesel** [comment]
Updated in the doc [here](https://github.com/standardhealth/shr-cli/wiki/CIMPL-Installation#macos-jekyll-installation).  Thanks for the suggestion!
