### ISSUE TITLE
Resolution of DeceasedStatus to deceased[x].boolean ==> doesn't work for DTSU3

### ISSUE THREAD

**Issue by saulakravitz** [standardhealth/shr-cli#190]
In [DSTU3](http://hl7.org/fhir/STU3/patient.html) looks like it would need to be deceased[x].DeceasedBoolean, and that too doesn't work.    SHould the tutorial advise to  map:

  DeceasedStatus maps to deceased[x]  

???

**Comment by cmoesel** [comment]
Yes, you are absolutely correct.  I've updated the tutorial:

![image](https://user-images.githubusercontent.com/2278253/56289915-10b18e00-60f0-11e9-9210-afd39ae81785.png)

Thanks for pointing this out!
