### ISSUE TITLE
https://github.com/standardhealth/shr-cli/wiki/Tutorial#cimpl-outputs : suggestion

### ISSUE THREAD

**Issue by saulakravitz** [standardhealth/shr-cli#191]
The text says: "By default, shr-cli takes CIMPL models and exports several files:"
Actually, "By default, shr-cli takes CIMPL models and exports files into these directories:"

The directory names are capitalized in the tutorial text, and lower case in real life.  I suggest making them consistent.

"Each of those generated files would take a considerable amount of time to create by hand, but CIMPL's concise syntax combined with the shr-cli generators allow for quick initial and subsequent drafts." ==> "Each of the generated files in these directories would take a considerable amount of time to create by hand, but CIMPL's concise syntax combined with the shr-cli generators allow for quick initial and subsequent drafts."

(BTW:  hoping my comments aren't perceived as pedantic...the tutorial is really nicely done, and worth polishing! I'm hoping a lot of people will be trying to read this text.)

**Comment by cmoesel** [comment]
I've reworked this section as suggested:

![image](https://user-images.githubusercontent.com/2278253/56291414-3f7d3380-60f3-11e9-9ea3-5fc5a43d0317.png)

No need to apologize for the feedback!  We appreciate the help!
