### ISSUE TITLE
https://github.com/standardhealth/shr-cli/wiki/Tutorial#fhir-output -- suggestion

### ISSUE THREAD

**Issue by saulakravitz** [standardhealth/shr-cli#192]
Suggesting that the user edit the OUTPUT of the CIMPL tools seems like a bad idea...like editing compiled code.  Can't the suggested changes be made at the input to the CIMPL process?

Also, since zoo/out is a directory, the instructions:
"cp ../zoo/out ." should be "cp -r ../zoo/out .", right?

**Comment by cmoesel** [comment]
Agreed -- and fixed:

![image](https://user-images.githubusercontent.com/2278253/56292751-badfe480-60f5-11e9-872a-b3514ca9d916.png)

Thanks again for helping us improve this document!
