### ISSUE TITLE
Fully Qualified Name -- grammar correction

### ISSUE THREAD

**Issue by saulakravitz** [standardhealth/shr-cli#194]
mixed singular/plural noun/verb in first sentence.   
Use of 'you' in 2nd sentence is to be avoided.

Current text:
"Note: While rare and considered bad practice, naming collisions between elements across multiple namespaces is possible. In the case of a naming collision (such as when a namespace Uses multiple namespaces that define an element with the same declared name), you would have to refer to the specific unique FQN instead of the declared name in element, field, and value definitions."

Proposed text:
"Note: While rare and considered bad practice, naming collisions between elements across multiple namespaces *are* possible. In the case of a naming collision (such as when a namespace Uses multiple namespaces that define an element with the same declared name), the specific unique FQN should be referenced instead of its declared name in element, field, and value definitions."

**Comment by markkramerus** [comment]
Not in current documentation. Closing.  PS -- We won't stop using 2nd person.
