### ISSUE TITLE
https://github.com/standardhealth/shr-cli/wiki/CIMPL-Documentation#value -- recommended change

### ISSUE THREAD

**Issue by saulakravitz** [standardhealth/shr-cli#195]
Current: "Defines what the element is. You are allowed to declare a value to be either a primitive or a DataElement."

Proposed: "Defines what the element is. Values can be declared as either a DataElement (e.g., CodeableConcept) or a primitive (e.g., string), as shown here."

**Comment by mlterryMitre** [comment]
@markkramerus - fixed locally on my laptop and only for CIMPL6 Reference Documentation. waiting on GitHub repo for publishing.

**Comment by markkramerus** [comment]
Overcome by events. No longer in current doc suite.
