### ISSUE TITLE
https://github.com/standardhealth/shr-cli/wiki/CIMPL-Documentation#no-constraint

### ISSUE THREAD

**Issue by saulakravitz** [standardhealth/shr-cli#196]
I don't understand this.  So, either I'm dense, or it isn't clear.

Here is the current text:

Keywords | Example
-- | --
     | 0..1 GeopoliticalLocation
     | Value: CodeableConcept
or | Value: unsignedInt or positiveInt

Questions:
- is or a keyword?  Or should it be deleted.
- is "Value:" equivalent to "1..1"?    so 1..1 unsignedInt  == Value: unsignedInt?   (If so, I'd get rid of Value in the next iteration of the syntax, and just leave the cardinality)

Experimentally, Value: CodeableConcept is equivalent to 1:1 CodeableConcept in an EntryElement, but not in an Element within that Entry Element.  From the zoo example, this works:
EntryElement: Animal
Value: DateOfBirth

This doesn't work:
  Element: DeceasedStatus
    Description: "An indication that the animal is no longer living, given by a boolean value which, when true, indicates the animal is deceased."
   1..1 boolean

**Comment by mlterryMitre** [comment]
`or` is an operator in human-readable text form.  This will be deleted from the keyword column.

**Comment by mlterryMitre** [comment]
@markkramerus - the `1..1 boolean` constraint could be unit-tested in our CIMPL6 test harness.

**Comment by mlterryMitre** [comment]
actually...come to think of it, `1..1 boolean` is a syntax error.  We could add it as a negative test in our CIMPL6 test harness instead and also change the tutorial for CIMPL5.

**Comment by markkramerus** [comment]
Overcome by events. Table no longer exists in current documentation.
