### ISSUE TITLE
https://github.com/standardhealth/shr-cli/wiki/CIMPL-Documentation#includes-code -- not clear

### ISSUE THREAD

**Issue by saulakravitz** [standardhealth/shr-cli#197]
Perhaps density of the reader, but I don't follow *this*:

The second example above expands the allowable codes in ProblemCategory to include #adverse_reaction. Unlike the first example, the value set does not precede the code, *because it has defined on ProblemCategory's parent using a from statement*.

**Comment by markkramerus** [comment]
Overcome by events. Not longer finding such statements in the current doc.
