### ISSUE TITLE
Slicing when discriminator is optional?

### ISSUE THREAD

**Issue by jmandel** [standardhealth/shr-cli#199]
https://chat.fhir.org/#narrow/stream/179177-conformance/topic/Slicing.20on.20an.20optional.20element captures discussion about one of the CIMPL-generated IGs, where [StructureDefinitions like this](http://standardhealthrecord.org/guides/mcode/StructureDefinition-shr-core-BodyHeight.json) include slicing defined when the discriminator is optional.

I *think* this is a bug, but would be good to see if the CIMPL team concurs!

**Comment by cmoesel** [comment]
Hi @jmandel -- will take a look!  Thanks for pointing us to it!

**Comment by cmoesel** [comment]
Included some more information at the chat link above, but in short, I agree that if we fix a code, we should set the card to `1..1`.  I _thought_ we were doing that, but apparently not.

**Comment by markkramerus** [comment]
Closing in favor of CIMPL-32 (Jira)
