### ISSUE TITLE
IG Publisher validates all examples located in the fhir_examples folder but are not related to the IG config

### ISSUE THREAD

**Issue by mlterryMitre** [standardhealth/shr-cli#202]
scenario:
- created FHIR examples that belong to mCODE and to usdrugformulary where examples are not shared between either.  All of these FHIR examples must be in the same folder.

result:
- if one runs shr-cli to create a usdrugformulary configuration (which doesn't include any profiles in mCODE), the IG publisher will try to validate all of the examples in the  fhir_examples directory and generate many errors of elements not found.

Workaround:
- temporarily move all of the unrelated fhir examples to a separate parking_lot directory and keep only those related to your FHIR IG.  Move all of the FHIR examples back to the fhir_examples directory prior to committing and merging to the shr_spec branch.

**Comment by markkramerus** [comment]
Moved to Jira, #CIMPL-31
