### ISSUE TITLE
"Tail Cardinality" Error

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-cli#25]
I'm getting an error that seems like a CLI bug. I don't think there is any reason the cardinality is invalid. The error goes away when the cardinality on severity is 0..*, but I get the following error when the cardinality is 0..1:

[19:35:15.073Z] ERROR shr: Cannot constrain cardinality to 0..1 because there is no tail cardinality max that can get us there (module=shr-fhir-export, shrId=cimi.clinical.assertion.Assertion, target=Condition, mappingRule="Severity maps to severity")

This happens at the mapping stage, because if I comment out the mapping rule, the error disappears. Verified the same behavior in 5.0.0 beta 4, 6, 7

This may be related: The profile on Condition has no diffs, and severity is missing from the snapshot. Something is going very wrong.

The specification is on the CIMI branch, specifically, a commit to the CIMI branch 8/12 about 3:43 pm.  

SHA # 9466c783e961ff7c7b5cf6745acb50b751376fe0

**Comment by Abhijay** [comment]
I managed to pinpoint why the tail-cardinality bug occurred, and it has to do with the way Namespaces are being defined. For instance, cimi_assertion.txt’s namespace is “cimi.clinical.assertion.” The extra path seems to throw off the FHIR exporter's method of retrieving cardinality from a path, which causes the cardinality information loss we noticed earlier. I can adjust that part to accept double period namespaces, but I’d have to do a decent amount of testing to make sure it isn’t affecting different parts of the tooling at all stages. 

Just to understand better, what’s the reason behind the “a.b.c” syntax vs the “a.b” syntax that we used throughout the SHR spec, and would you consider it to be a necessary feature?

**Comment by markkramerus** [comment]
Excellent analysis. It makes perfect sense. 
CIMI uses this structure. There are multiple modules within the "clinical" modules. I was trying to preserve this structure, but it is not 100% necessary.  For now, I'll remove one of the dots in the path, and press forward. Let's keep this open and return to it at a later time.
Thanks so much!

**Comment by Abhijay** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tail Cardinality Error](https://trello.com/c/cSDc0RiA/1-tail-cardinality-error)

**Comment by markkramerus** [comment]
Overcome by events. Haven't seen this bug for a long time.
