### ISSUE TITLE
Error on "is type" statement, but looks legal

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-cli#43]
Got an error trying to constrain ImmunizationGiven.Outcome to ref(AdverseReaction) as follows:

Element:		Outcome
Value:		ref(Finding)

EntryElement:	AdverseReaction
Based on:	Finding

EntryElement:	ImmunizationGiven
Based on:	ImmunizationAction
			Outcome is type ref(AdverseReaction)  // field inherited from ImmunizationAction

Resulting error message:
ERROR shr: Cannot constrain type of IdentifiableValue<shr.base.Outcome> to shr.adverse.AdverseReaction. ERROR_CODE:12014 (module=shr-expand, shrId=shr.immunization.ImmunizationGiven)

Looks like this is legal construct, isn't it?

**Comment by cmoesel** [comment]
I don't think this is legal.  `AdverseReaction` is based on `Finding`, but neither `AdverseReaction` nor `Finding` are based on `Outcome`.  `Outcome`'s _value_ is `Finding`, but that doesn't mean you can cast a `Finding` to an `Outcome`.  `Finding` would have to be _based on_ `Outcome` for that to work.

**Comment by markkramerus** [comment]
The statement should have been "Outcome value is type ref(AdverseReaction)".
My mistake. No bug here.
