### ISSUE TITLE
Error message produces CIMCORE - and that's too verbose

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-cli#59]
Certain error messages in 5.4 and 5.5 are printing out lengthy CIMCORE dumps with the error message appended at the end. I like the explicitness of the message, but overall it is too much information.  Get a few of these and the scrolling up and down becomes a nightmare. 

Here's an example: 

[20:20:23.898Z] ERROR shr:  (module=shr-json-schema-export, shrId=shr.behavior.IntravenousDrugUse)
    Element {
      "name": "ObservationComponent",
      "namespace": "shr.finding",
      "fqn": "shr.finding.ObservationComponent",
      "isEntry": false,
      "isAbstract": true,
      "description": "A simplified, non-separable observation consisting of a observation code, value (or value absent reason), reference range, and interpretation. The subject of the observation component is the same as in the parent observation.",
      "value": {
        "valueType": "ChoiceValue",
        "card": {
          "min": 0,
          "max": 1
        },
        "options": [
          {
            "fqn": "shr.core.Quantity",
            "valueType": "IdentifiableValue"
          },
          {
            "fqn": "shr.core.CodeableConcept",
            "valueType": "IdentifiableValue"
          },
          {
            "fqn": "string",
            "valueType": "IdentifiableValue"
          },
          {
            "fqn": "shr.core.Range",
            "valueType": "IdentifiableValue"
          },
          {
            "fqn": "shr.core.Ratio",
            "valueType": "IdentifiableValue"
          },
          {
            "fqn": "shr.core.Attachment",
            "valueType": "IdentifiableValue"
          },
          {
            "fqn": "time",
            "valueType": "IdentifiableValue"
          },
          {
            "fqn": "dateTime",
            "valueType": "IdentifiableValue"
          },
          {
            "fqn": "shr.core.TimePeriod",
            "valueType": "IdentifiableValue"
          },
          {
            "fqn": "shr.core.IntegerQuantity",
            "valueType": "IdentifiableValue"
          }
        ]
      },
      "fields": [
        {
          "fqn": "shr.finding.ValueAbsentReason",
          "valueType": "IdentifiableValue",
          "card": {
            "min": 0,
            "max": 1
          }
        },
        {
          "fqn": "shr.finding.ObservationCode",
          "valueType": "IdentifiableValue",
          "card": {
            "min": 1,
            "max": 1
          }
        },
        {
          "fqn": "shr.finding.Interpretation",
          "valueType": "IdentifiableValue",
          "card": {
            "min": 0,
            "max": 1
          }
        },
        {
          "fqn": "shr.finding.ReferenceRange",
          "valueType": "IdentifiableValue",
          "card": {
            "min": 0
          }
        }
      ]
    } **lacked a field or a value that matched shr.environment.ExposureMethod as part of constraint** {
      "type": "code",
      "value": {
        "system": "http://ncimeta.nci.nih.gov",
        "code": "C0021494"
      },
      "lastModifiedBy": "shr.behavior.IntravenousDrugUse"
    }

**Comment by Abhijay** [comment]
(Just housekeeping.)
This is fixed in the following:
https://github.com/standardhealth/shr-models/pull/21
https://github.com/standardhealth/shr-json-schema-export/pull/5

But these PRs are not yet merged in so I'll wait for that before closing.
