### ISSUE TITLE
Regression between 5.2.3 and 5.3 (still present in 5.6)

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-cli#65]
I just did a commit (SHIMI branch build # f1b515f8ffb08f67aeb6c2715b7b1846a6344052 at about 1:48 pm on 3/3/2018)  that includes an intentional error to demonstrate a crash in CLI. The actual problem is that ExposureToAgent.ObservationCode has no cardinality. If you run CLI 5.2.3, the problem is handled smoothly with appropriate error messages. In 5.6.0, not so -- it crashes with no way for the user to figure out the problem.

**Comment by cmoesel** [comment]
@Abhijay -- I've pushed fixes to `null_card_fix` branches on `shr-models` and `shr-expand`.  Since I think you're already working in those repos, do you think it makes sense for you to merge in the changes to your branches and release them all together?

**Comment by markkramerus** [comment]
Tried this out in 6.5.0. I get a good error message:
[15:18:06.098Z] ERROR shr: No cardinality found for field Purpose in Address. ERROR_CODE:12004 (module=shr-expand, shrId=obf.datatype.Address)

Closing.
