### ISSUE TITLE
HIGH priority: "Is type" constraint fails to appear in FHIR

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-cli#67]
Version 5.6.0... in the shimi branch...
1) Subject.Value is a choice: ref(Patient) or ref(Group) or ref(Device) or ref(Location) or ref(RelatedPerson) or ref(Organization)
2) In HER2ReceptorStatus (and other places) I have the constraint: **Subject value is type ref(Patient)**
In mapping, I have Subject maps to (Observation) subject.
3) The resulting IG (differential view) has: Observation.subject =  Reference(SHR Patient Profile), Reference(SHR Group Profile), Reference(SHR Device Profile), Reference(SHR Geoposition Profile)

This should be Reference(SHR Patient Profile), correct?

**Comment by markkramerus** [comment]
PS - Why Geoposition Profile?

**Comment by cmoesel** [comment]
I agree that the expectation is that it would narrow the choice to just `Reference (SHR Patient Profile)`.  I'll have to take a look to see what is going on here.  Based on our IM conversation, however, I will no longer treat this as highest priority.

**Comment by markkramerus** [comment]
Fixed a while ago. Closing.
