### ISSUE TITLE
Why isn't Range a "no-diff" profile?

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-cli#68]
It seems like there are no differences between SHR and FHIR definitions of Range. This could potentially be a bug.

**Comment by cmoesel** [comment]
I'll look into this.

**Comment by cmoesel** [comment]
I've confirmed that on the current `shimi` branch, the tools produce a profile for `Range`, but the `differential` on the profile just repeats the `low` and `high` types without changing them.

The intent is that profiles like this are suppressed since they do not represent any actual change.

**Comment by markkramerus** [comment]
Not seeing this type of bug any longer. Assuming it has been fixed.
