### ISSUE TITLE
PercentageRange Profile isn't right

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-cli#69]
In Shimi branch, I have defined:
	Element:		PercentageRange
	Based on:		Range
	Description:	"A range of percentage values."
	0..1			LowerBound value is type Percentage
	0..1			UpperBound value is type Percentage

but the profile shr-oncology-PercentageRange shows type SimpleQuantity. 
The Percentage definition is:
	Element:		Percentage
	Based on:	SimpleQuantity
	Concept:		MTH#C0439165
	Description:	"A percentage value where 100.0 represents 100%."
				Units.Coding is UCUM#%

**Comment by cmoesel** [comment]
I'll look into this.

**Comment by cmoesel** [comment]
Confirmed reproducible bug using current `shimi` branch.  Will need to debug to see what the cause is.

**Comment by markkramerus** [comment]
Moved to CIMPL-41.
