### ISSUE TITLE
shr is built into tooling

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-cli#70]
I'm on the may-2018-ballot branch. I tried to remove the "shr." prefix from the namespaces. I was partly successful, but couldn't get rid of shr.base and shr.core. Didn't dig deeper than that but I know it has to do with the fully qualified name of CodeableConcept, Coding, and perhaps something else.

**Comment by markkramerus** [comment]
The other one that builds in "shr" is Entry.

**Comment by cmoesel** [comment]
Yes, you're exactly right -- because the tooling has to treat `Coding`, `CodeableConcept`, `Quantity`, and `Entry` specially, the fully qualified names are hard-coded into the tooling.  I'm not sure how we can get around this short of building those element definitions into the tooling itself.

**Comment by markkramerus** [comment]
Retiring. The issue has been "solved" by building "concept" into the framework, "Quantity" (which is a strange hybrid of concept and structure) partly into the framework, and removing Entry (in progress, SHRO-819).
