### ISSUE TITLE
Not getting value set expansions (IG creation)

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-cli#72]
Snomed should be supported, but I'm getting no codes from the terminology services. Not sure why. Here's an example of the error message from a value set page:

Expansion
Error expanding ValueSet "null: Error unmarshalling resource: Unable to provide support for code system http://snomed.info/sct version http://snomed.info/sct/731000124108

Could it possibly be that http://snomed.info/sct/731000124108 is not a valid version name?

**Comment by cmoesel** [comment]
Can you provide more detail regarding what value set this pertains to (in what branch)?  I can't find any references to `731000124108` in the `shimi` or `may-2018-ballot` branches.

That said, I did find this guidance regarding SNOMED versions:
http://hl7.org/fhir/STU3/snomedct.html#4.2.1.0.2

And I found this value set in the FHIR spec that seems to use the version you referenced:
http://www.hl7.org/fhir/valueset-consistency-type.xml.html

But without see how you were using it in the SHR spec, it's hard to determine what's going on.

**Comment by markkramerus** [comment]
It's not in the spec at all. The error message is in the IG, on the value sets page. Sorry I didn't make that more clear.

**Comment by markkramerus** [comment]
We haven't had this problem in a while. Closing.
