### ISSUE TITLE
IG contains Elements and Abstract Elements

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-cli#73]
It seems if there is an element with an explicit mapping to FHIR, then the IG will have a profile for that element, even if that element is abstract element (or a simple element). Sometimes if is beneficial to map an abstract parent class so all children will inherit the map, but only children of that parent should become documented profiles.

**Comment by cmoesel** [comment]
You are correct: current behavior will output a profile for _any_ element (including abstract and non-entry elements) -- except if it creates a "no-diff" profile.  We can change the behavior such that only _entries_ get profiles by default, but it will still need to produce profiles for elements or abstract elements if any entry references them.

Would you like us to add this to the backlog?  I think it would be a relatively trivial fix.

**Comment by markkramerus** [comment]
Sounds like it won't make much difference. A low priority.  The issue really is that it dilutes the content of an IG.

**Comment by markkramerus** [comment]
Moved to JIRA issue tracker, CIMPL-39.
