### ISSUE TITLE
HIGH PRIORITY: Observation Components in profile are missing valueQuantity 

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-cli#75]
See the IG page for HER2ReceptorStatusISH (url ends in StructureDefinition-oncology-HER2ReceptorStatusISH.html) in ballot IG, generated from may-2018-ballot branch.

Note that valueQuantity is missing from the profile in two of the components. I've looked at the CIMPL spec and it seems ok. Not sure how widespread this problem might be (does it affect other component value types?)

![capture](https://user-images.githubusercontent.com/492232/37409331-791f42f4-2774-11e8-84f1-ef3efa7cad06.JPG)

**Comment by cmoesel** [comment]
Fixed.
![missing_quantity](https://user-images.githubusercontent.com/2278253/37807842-de142f94-2e1d-11e8-8203-5258bff4cadf.png)

**Comment by markkramerus** [comment]
Yes
