### ISSUE TITLE
Schema Exporter

### ISSUE THREAD

**Issue by cmoesel** [standardhealth/shr-cli#9]
Currently, the only exchange or storage mechanism for SHR instance data is FHIR.  Ideally, SHR should have a native exchange/storage format that is simpler than FHIR and a more direct 1:1 mapping to SHR.  This would likely be best accomplished via an exporter that generates JSON Schema for SHR data elements.

**Comment by jgibson** [comment]
This is under development in https://github.com/standardhealth/shr-json-schema-export. Corresponding changes to this project are on the [json-schema-export](https://github.com/standardhealth/shr-cli/tree/json-schema-export) branch.

**Comment by markkramerus** [comment]
Done a long time ago. Closing.
