### ISSUE TITLE
Wrong Value Set References in IG (Ballot comment#16543)

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-cli#99]
A voter noticed that the three components of BreastCancerHistologicGrade (TubuleFormationScore, NuclearPleomorphismScore, MitoticCountScore) all appear to be bound to NottinghamCombinedGradeVS. In the CIMPL source, they have their own value sets (TubuleFormationScoreVS, NuclearPleomorphismScoreVS, MitoticCountScoreVS). So it appears something got messed up in listing the value sets in the FHIR exporter. 
See http://hl7.org/fhir/us/breastcancer/StructureDefinition-oncology-BreastCancerHistologicGrade.html

**Comment by cmoesel** [comment]
This appears to be fixed now.  I've just run my latest tooling (not yet released) against the _shimi_ branch and the component value sets are different (with the exception of NottinghamComponentNullVS, but I confirmed that this matches the CIMPL, so if it's unintended, the CIMPL needs to change).

![image](https://user-images.githubusercontent.com/2278253/42912723-e6c3181e-8abe-11e8-8d03-a93cd06b6231.png)

**Comment by cmoesel** [comment]
I'll close this once it's confirmed to be working in a release SHR-CLI.

**Comment by markkramerus** [comment]
Closing.
